### ISSUE TITLE
Bump BD Version to 1.4.0

### ISSUE THREAD

**Issue by IamNickerson** [Strencher/BdBrowser#18] opened 2022-01-31 14:01 UTC
Hi,
Can u bump the Version of BD Browser to latest version of BD which is 1.4.0 as new features got introduced to it. Some plugins aren't that much compatible with current BD version which BD browser is using now. (And it will also stop prompting to update as the update button is useless it says to go get the installer)
![image](https://user-images.githubusercontent.com/61643704/151806930-55f1ff41-1a0e-4ef0-a6e6-f5ec17a7c0b1.png)

**Comment by dav1312** [comment] 2022-01-31 15:02
Duplicate of #17

**Closed as completed** 2022-01-31 15:17 UTC

**Comment by IamNickerson** [comment] 2022-01-31 16:05
Duplication of #17?

**Comment by IamNickerson** [comment] 2022-01-31 16:06
I don't get it?

**Comment by IamNickerson** [comment] 2022-01-31 16:07
Oh okay I can click on it. ![Screenshot_2022-01-31-20-07-19-56_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/61643704/151829372-97190cdf-4736-41af-8dc1-b26f401d92e9.jpg)

**Comment by IamNickerson** [comment] 2022-01-31 16:08
Wait what will happen to people who are still using it?
